name: many-faced-god

services:
  app:
    image: many-faced-god-app:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - many-faced-god-network
      - netheril-integration
      - vivaldi-integration
    depends_on:
      - db

  webserver:
    build:
      context: ./docker/nginx
    image: many-faced-god-nginx:latest
    restart: unless-stopped
    ports:
      - "8765:80"
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - many-faced-god-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - many-faced-god-db-data:/var/lib/mysql
    networks:
      - many-faced-god-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u\"$${MYSQL_USER}\" -p\"$${MYSQL_PASSWORD}\" --silent"]
      interval: 2s
      timeout: 5s
      retries: 15

networks:
  many-faced-god-network:
    external: true
  netheril-integration:
    external: true
  vivaldi-integration:
    external: true

volumes:
  many-faced-god-db-data:
